### ISSUE TITLE
Investigate possible use of zerocopy

### ISSUE THREAD

**Issue by ionut-arm** [parallaxsecond/parsec-interface-rs#10]
Have a look at https://docs.rs/zerocopy/0.2.8/zerocopy/ and find out whether this could be used to speed up our processing of requests/responses.

**Comment by hug-dev** [comment]
If I understood correctly, that would allow us to do the (de)serializing in place from the bytes buffer instead of having to do the copy from(to) the bytes to(from) the structure?

**Comment by ionut-arm** [comment]
This is what I understood too

**Comment by hug-dev** [comment]
Would be nice, as a pre-requisite for this task, to add some bench tests to be able to compare the performences before/after 💨

**Comment by ionut-arm** [comment]
tbh I think parsec will mostly be limited by the performance of the underlying hardware module :( but we could maybe see something with mbed crypto

**Comment by hug-dev** [comment]
What about a virtual provider then, a test provider or a dummy provider? Which implements the `Provide` trait, maybe uses the KIM but mock the `Result` (maybe returns `NotImplemented`)? That way we would test the performance of the whole stack but the hardware backend. Could also be usefull to be included by default so that Parsec "works" even if not providers selected.

However, another point that you make is that if the time spent in Parsec stack is negligible to the time spent in the actual provider, it does not probably make sense to optimise if that reduces code readability/simplicity or increases compile time. We could do bench tests comparing the virtual provider to the real ones to see the differences :)

**Comment by ionut-arm** [comment]
We could! Alas, just as with this ticket, I don't think the dummy provider is worth considering for now. 
It's probably worth discussing this in a Parsec meeting at some point, when we're on track for a provider-ready parsec
